---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
Member:
  extensions:
    - MemberExtension
SiteConfig:
  extensions:
    - SiteConfigExtension
ReportSection:
  extensions:
    - BlocksSiteTreeExtension
Block:
  extensions:
    - BlockExtension
LeftAndMain:
  extra_requirements_css:
    - themes/division-reports/dist/css/cms.css
BlogPost:
  default_sort: Sort