---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
Member:
  extensions:
    - MemberExtension
SiteConfig:
  extensions:
    - SiteConfigExtension
ReportSection:
  extensions:
    - BlocksSiteTreeExtension
